
package:
  name: ringclosingmm
  version: {{ environ.get('RINGCLOSINGMM_VERSION', '') }}

source:
  # For local testing, use path
  path: ..
  
  # For conda-forge, use PyPI or GitHub release
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: REPLACE_WITH_ACTUAL_SHA256
  
  # Or use GitHub release:
  # url: https://github.com/denoptim-project/RingClosingMM/archive/v{{ version }}.tar.gz
  # sha256: REPLACE_WITH_ACTUAL_SHA256

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - rc-optimizer = ringclosingmm.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - wheel
  
  run:
    - python >=3.8
    - numpy >=1.20.0
    - scipy >=1.7.0
    - openmm >=7.7.0

test:
  imports:
    - ringclosingmm
  commands:
    - rc-optimizer --help
  requires:
    - pytest >=6.0

about:
  home: https://github.com/denoptim-project/RingClosingMM
  license: AGPL-3.0
  license_file: LICENSE
  summary: Ring closing molecular modeling using an OpenMM engine
  description: |
    The RingClosingMM is a molecular modeling tool for identifying 
    ring-closing conformations. It uses OpenMM engine and SciPy optimizers 
    combined with a special force field that favors ring-closing bond 
    formation.
  doc_url: https://github.com/denoptim-project/RingClosingMM/blob/main/README.md
  dev_url: https://github.com/denoptim-project/RingClosingMM

extra:
  recipe-maintainers:
    - marco-foscato

